apiVersion: v2
# upstream version
appVersion: 1.22.1
name: kubeedge-cloudcore
# giantswarm chart version
version: 0.3.0
annotations:
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.upstream-chart-url: "https://github.com/kubeedge/kubeedge/tree/master/manifests/charts/cloudcore"
  io.giantswarm.application.upstream-chart-version: "1.22.1"
description: The KubeEdge cloudcore component.
home: https://github.com/giantswarm/kubeedge-cloudcore-app
icon: https://s.giantswarm.io/app-icons/kubeedge/1/light.png
keywords:
  - edge
  - iot
  - kubernetes
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
dependencies:
  - name: kubeedge-cloudcore-crds
    version: 1.22.0
sources:
  - https://github.com/kubeedge/kubeedge
