# We have to use the cluster-admin role for the hook service account
# because the rbac creation job needs elevated permissions in order
# to create the necessary rbac. The rbac below and the associated
# service account are always deleted after the job completes
# (regardless of the job's success). This is to ensure that the service
# account and the elevated rbac are not left in the cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{- include "kubeEdgeHookServiceAccount" . }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "cluster-admin"
subjects:
  - kind: ServiceAccount
    name: "{{- include "kubeEdgeHookServiceAccount" . }}"
    namespace: "{{ .Release.Namespace }}"
