apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{- include "kubeEdgeCiliumHookServiceAccount" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
{{- if and (.Values.cloudCore.service.enable) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{- include "kubeEdgeServiceHookServiceAccount" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    "helm.sh/hook-weight": "0"
{{- end }}
