apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{- include "kubeEdgeHookServiceAccount" . }}"
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["cilium", "cilium-kubeedge"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{- include "kubeEdgeHookServiceAccount" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{- include "kubeEdgeHookServiceAccount" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{- include "kubeEdgeHookServiceAccount" . }}"
    namespace: "{{ .Release.Namespace }}"