{{- if .Capabilities.APIVersions.Has "policy.giantswarm.io/v1alpha1/PolicyException" }}
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  name: kubeedge-iptables-manager
  namespace: policy-exceptions
spec:
  policies:
  - disallow-capabilities
  - disallow-capabilities-strict
  - disallow-host-namespaces
  - disallow-privilege-escalation
  - require-run-as-nonroot
  - restrict-seccomp-strict
  targets:
  - kind: DaemonSet
    names:
    - cloud-iptables-manager*
    namespaces:
    - kubeedge
---
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  name: kubeedge-mosquitto
  namespace: policy-exceptions
spec:
  policies:
  - disallow-capabilities-strict
  - disallow-host-namespaces
  - disallow-host-path
  - disallow-privilege-escalation
  - require-run-as-nonroot
  - restrict-seccomp-strict
  - restrict-volume-types
  targets:
  - kind: DaemonSet
    names:
    - edge-eclipse-mosquitto*
    namespaces:
    - kubeedge
---
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
  name: kubeedge-cloudcore
  namespace: policy-exceptions
spec:
  policies:
  - disallow-capabilities-strict
  - disallow-host-path
  - disallow-privilege-escalation
  - disallow-privileged-containers
  - require-run-as-nonroot
  - restrict-seccomp-strict
  - restrict-volume-types
  targets:
  - kind: Deployment
    names:
    - cloudcore*
    namespaces:
    - kubeedge
{{- end }}
